# Generated by Django 4.2.1 on 2023-05-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seg_cargas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargas',
            name='ata',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='atd',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='cotizacion',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='estado',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='incoterm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='mawb',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='retiro',
            field=models.DateField(blank=True),
        ),
    ]
